myblog/blog/urls.py
from django.urls import path


from . import views

urlpatterns = [
  path('<int:year>/<int:month>/<int:day>/<int:pk>-<slug:slug>/', views.EntryDetail.as_view(), name='entry_detail'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import include, path
from myblog import views
import blog.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('', include(blog.urls)),
]

myblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

import hashlib


class Entry(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)
    slug = models.SlugField(default='', editable=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "entries"      

    def get_absolute_url(self):
        kwargs = {'year': self.created_at.year,
                  'month': self.created_at.month,
                  'day': self.created_at.day,
                  'slug': self.slug,
                  'pk': self.pk}
        return reverse('entry_detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class Comment(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)
    

    def __str__(self):
        return self.body
    
    def gravatar_url(self):
        # Get the md5 hash of the email address
        md5 = hashlib.md5(self.email.encode())
        digest = md5.hexdigest()

        return 'http://www.gravatar.com/avatar/{}'.format(digest)

myblog/blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
    
    def __init__(self, *args, **kwargs):
        self.entry = kwargs.pop('entry')   # the blog entry instance
        super().__init__(*args, **kwargs)

    def save(self):
        comment = super().save(commit=False)
        comment.entry = self.entry
        comment.save()
        return comment

myblog/blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView

from .forms import CommentForm
from .models import Entry


class EntryDetail(CreateView):
    model = Entry
    template_name = 'blog/entry_detail.html'
    form_class = CommentForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['entry'] = self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['entry'] = self.get_object()
        return d
    
    def get_success_url(self):
        return self.get_object().get_absolute_url()

myblog/myblog/views.py
from django.views.generic import ListView

from blog.models import Entry


class HomeView(ListView):
    template_name = 'index.html'
    queryset = Entry.objects.order_by('-created_at')

myblog/templates/_entry.html
<article class="card text-center" >
    <div class="card-divider" style="justify-content: center;">
        <h2 ><a href="{{ entry.get_absolute_url }}" >{{ entry.title }}</a></h2>
    </div>
    <div class="card-section">
        <p class="subheader">
            <time>{{ entry.modified_at|date }}</time>
        </p>

        <p>
            {{ entry.body|linebreaks }}
        </p>
    </div>
</article>

myblog/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>My Blog</title>
    <link rel="stylesheet" href="{%_static "css/foundation.css" %}">
</head>
<body>
    <section class="grid-x ">
        <header class="cell">
            <h1 class="text-center">Welcome to My Blog</h1>
            <hr>
        </header>
    </section>

    <section class="grid-x grid-padding-x align-center">

        <div class="cell large-8">
            {% block content %}{% endblock %}
        </div>

        <div class="cell large-4">
            <h3>About Me</h3>
            <p>I am a Python developer and I like Django.</p>
            <h3>Recent Entries</h3>
            {% entry_history %}
        </div>

    </section>

</body>
</html>

myblog/templates/blog/_entry_history.html
<ul>
    {% for entry in entries %}
        <li>{{ entry.title }}</li>
    {% empty %}
        <li>No recent entries</li>
    {% endfor %}
</ul>

myblog/templates/blog/entry_detail.html
{% extends "base.html" %}

{% block content %}
    {% include "_entry.html" with entry=entry only %}
    <hr>
    <h4>Comments</h4>
    {% for comment in entry.comment_set.all %}
        <p>
            <em>Posted by {{ comment.name }}</em>
            <img src="{{ comment.gravatar_url }}" align="left">
        </p>
        {{ comment|linebreaks }}
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
    <h5>Add a comment</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input class="button" type="submit" value="Create Comment">
    </form>
{% endblock %}

myblog/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for entry in entry_list %}
        {% include "_entry.html" with entry=entry only %}
        {% empty %}
            <p>No blog entries yet.</p>
    {% endfor %}

{% endblock content %}